// Code generated by ogen, DO NOT EDIT.
package api

type DeleteUserRes interface {
	deleteUserRes()
}

type GetUserRes interface {
	getUserRes()
}

type PostUserRes interface {
	postUserRes()
}

type PutUserRes interface {
	putUserRes()
}
